title: Fisher Ski klub Šumava Vimperk
encoding: UTF-8
sass:
    sass_dir: css
    style: compressed
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - jekyll-bootstrap-minimal-master.zip
